name: Appium Workflow

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload Static Appium Test Report
      uses: actions/upload-artifact@v4
      with:
        name: appium-test-report
        path: tests/appium_test_report.xlsx
        retention-days: 14
